remote_theme: mmistakes/minimal-mistakes
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

name: "Tom Reitz"
title: "Tom Reitz"
subtitle: "exploring tech, data, and life"
description: "Tom is a technology professional based in Madison WI"
url: "https://tomreitz.com"

include: ["_pages", "_posts", "_book-reviews", "_projects"]

logo: "/assets/logo.png"

atom_feed:
  hide: true

search: true
lunr:
  search_within_pages: true

collections:
  posts:
    output: true
    permalink: /:collection/:path/
  book-reviews:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
    order:
      - 2023-12-23-dbt_synth_data.md
      - 2023-12-23-earthmover.md
      - 2023-12-23-lightbeam.md
      - 2021-05-05-age-estimation-from-rhytides.md
      - 2021-05-01-logservatory.md
      - 2021-02-13-the-effecto-of-redistricting.md
      - 2020-12-11-aws-category-explorer.md
      - 2018-12-11-on-gerrymandering.md



defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      mathjax: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      mathjax: true
  # _book-reviews
  - scope:
      path: ""
      type: book-reviews
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      mathjax: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      mathjax: true

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/tom.reitz"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/t0mreitz"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/user/tomreitz"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tomreitz/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tomreitz"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
