remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

name: "Tom Reitz"
description: "Tom is a technology professional based in Madison WI"
url: "https://tomreitz.com"
logo: "/assets/logo.png"
